src/Entity/TaskListItem.php
<?php

namespace App\Entity;

use App\Repository\TaskListItemRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TaskListItemRepository::class)
 */
class TaskListItem
{
    public const COMPLETE = 1;
    public const NOT_COMPLETE = 0;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=1023, nullable=true)
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity=TaskList::class, inversedBy="taskListItems")
     * @ORM\JoinColumn(nullable=false)
     */
    private $task_list;

    /**
     * @ORM\Column(type="smallint")
     */
    private $status;

    /**
     * @ORM\Column(type="integer")
     */
    private $created_at;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $updated_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getTaskList(): ?TaskList
    {
        return $this->task_list;
    }

    public function setTaskList(?TaskList $task_list): self
    {
        $this->task_list = $task_list;

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    public function setStatus(int $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getCreatedAt(): ?int
    {
        return $this->created_at;
    }

    public function setCreatedAt(int $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?int
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?int $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }
}

src/Form/TaskListItemType.php
<?php

namespace App\Form;

use App\Entity\TaskListItem;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TaskListItemType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('description', TextareaType::class);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => TaskListItem::class,
        ]);
    }
}

src/Controller/TaskListItemController.php
<?php

namespace App\Controller;

use App\Entity\TaskList;
use App\Entity\TaskListItem;
use App\Form\TaskListItemType;
use App\Repository\TaskListItemRepository;
use App\Repository\TaskListRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\HttpException;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/task-list-item")
 */
class TaskListItemController extends AbstractController
{
    /**
     * @Route("/new/{id}", name="app_task_list_item_new", methods={"GET", "POST"})
     */
    public function new(
        Request $request,
        TaskListItemRepository $taskListItemRepository,
        ?TaskList $taskList
    ): Response
    {
        if ($taskList === null) {
            throw new HttpException(404, 'Task list not found');
        }

        $taskListItem = new TaskListItem();
        $taskListItem->setTaskList($taskList);
        $form = $this->createForm(TaskListItemType::class, $taskListItem);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $taskListItemRepository->add($taskListItem);
            return $this->redirectToRoute(
                'app_task_list_show',
                ['id' => $taskList->getId()],
                Response::HTTP_SEE_OTHER
            );
        }

        return $this->render('task_list_item/new.html.twig', [
            'task_list_item' => $taskListItem,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="app_task_list_item_show", methods={"POST"})
     */
    public function changeStatus(TaskListItem $taskListItem)
    {

    }

    /**
     * @Route("/{id}/change-status", name="app_task_list_item_show", methods={"POST"})
     * @param Request $request
     * @param TaskListItem $taskListItem
     * @param TaskListItemRepository $taskListItemRepository
     * @param TaskListRepository $taskListRepository
     * @return Response
     * @throws \Doctrine\ORM\NonUniqueResultException
     * @throws \Doctrine\ORM\ORMException
     * @throws \Doctrine\ORM\OptimisticLockException
     */
    public function show(
        Request $request,
        TaskListItem $taskListItem,
        TaskListItemRepository $taskListItemRepository,
        TaskListRepository $taskListRepository
    ): Response
    {
        $status = (int) $request->get('status');
        if ($this->isCsrfTokenValid($taskListItem->getId() . 'change-status', $request->request->get('_token'))) {
            $taskListItemRepository->changeStatus($taskListItem, $status);
        } else {
            return $this->json(['success' =>  false]);
        }

        $taskListStatus = $taskListItemRepository->isAllCompleted($taskListItem);
        $taskListRepository->changeStatus($taskListItem->getTaskList(), $taskListStatus);

        return $this->json(['success' =>  true]);
    }

    /**
     * @Route("/{id}/edit", name="app_task_list_item_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, ?TaskListItem $taskListItem, TaskListItemRepository $taskListItemRepository): Response
    {
        if ($taskListItem === null) {
            throw new HttpException(404, 'Task list item not found');
        }

        $form = $this->createForm(TaskListItemType::class, $taskListItem);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $taskListItemRepository->add($taskListItem);
            return $this->redirectToRoute(
                'app_task_list_show',
                ['id' => $taskListItem->getTaskList()->getId()],
                Response::HTTP_SEE_OTHER
            );
        }

        return $this->render('task_list_item/edit.html.twig', [
            'task_list_item' => $taskListItem,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="app_task_list_item_delete", methods={"POST"})
     */
    public function delete(
        Request $request,
        ?TaskListItem $taskListItem,
        TaskListItemRepository $taskListItemRepository
    ): Response
    {
        if ($taskListItem === null) {
            throw new HttpException(404, 'Task list item not found');
        }

        $taskListId = $taskListItem->getTaskList()->getId();
        if ($this->isCsrfTokenValid('delete'.$taskListItem->getId(), $request->request->get('_token'))) {
            $taskListItemRepository->remove($taskListItem);
        }

        return $this->redirectToRoute(
            'app_task_list_show',
            ['id' => $taskListId],
            Response::HTTP_SEE_OTHER
        );
    }
}

templates/task_list_item/_delete_form.html.twig
<form method="post" action="{{ path('app_task_list_item_delete', {'id': task_list_item.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ task_list_item.id) }}">
    <button class="btn btn-delete">Delete</button>
</form>

templates/task_list_item/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/task_list_item/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit TaskListItem{% endblock %}

{% block body %}
    <h1>Edit TaskListItem</h1>

    {{ include('task_list_item/_form.html.twig', {'button_label': 'Update'}) }}

    <a class="btn btn-primary" href="{{ path('app_task_list_item_index') }}">back to list</a>

    {{ include('task_list_item/_delete_form.html.twig') }}
{% endblock %}

templates/task_list_item/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}TaskListItem index{% endblock %}

{% block body %}
    <h1>TaskListItem index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Description</th>
                <th>Status</th>
                <th>Created_at</th>
                <th>Updated_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for task_list_item in task_list_items %}
            <tr>
                <td>{{ task_list_item.id }}</td>
                <td>{{ task_list_item.name }}</td>
                <td>{{ task_list_item.description }}</td>
                <td>{{ task_list_item.status }}</td>
                <td>{{ task_list_item.createdAt }}</td>
                <td>{{ task_list_item.updatedAt }}</td>
                <td>
                    <a href="{{ path('app_task_list_item_show', {'id': task_list_item.id}) }}">show</a>
                    <a href="{{ path('app_task_list_item_edit', {'id': task_list_item.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a class="btn btn-primary" href="{{ path('app_task_list_item_new') }}">Create new</a>
{% endblock %}

templates/task_list_item/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New TaskListItem{% endblock %}

{% block body %}
    <h1>Create new TaskListItem</h1>

    {{ include('task_list_item/_form.html.twig') }}

    <a class="btn btn-primary btm-margin-top" href="{{ path('app_task_list_show', {'id': task_list_item.getTaskList.id}) }}">Back</a>
{% endblock %}

templates/task_list_item/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}TaskListItem{% endblock %}

{% block body %}
    <h1>TaskListItem</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ task_list_item.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ task_list_item.name }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ task_list_item.description }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ task_list_item.status }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ task_list_item.createdAt }}</td>
            </tr>
            <tr>
                <th>Updated_at</th>
                <td>{{ task_list_item.updatedAt }}</td>
            </tr>
        </tbody>
    </table>

    <a class="btn btn-primary" href="{{ path('app_task_list_item_index') }}">back to list</a>

    <a class="btn btn-primary" href="{{ path('app_task_list_item_edit', {'id': task_list_item.id}) }}">edit</a>

    {{ include('task_list_item/_delete_form.html.twig') }}
{% endblock %}